### ISSUE TITLE
An internal error occurred during: "TURNUS Orcc Profiler".

### ISSUE THREAD

**Issue by robstewart57** [turnus/turnus#2]
When selecting TURNUS in "Profile As", I see the error `An internal error occurred during: "TURNUS Orcc Profiler". net.sf.orcc.util.OrccLogger.warnRaw(Ljava/lang/String;)V` . Here's a screencast of the behaviour: http://www.macs.hw.ac.uk/~rs46/files/turnus.ogv

Thanks.

**Comment by casalebrunet** [comment]
we had a conf call with @robstewart57 on Jan 13th 2015 where the devel version was installed and checked
